<a href="https://colab.research.google.com/github/NADIYAHAQILAHPUTRIH/data_science_w1/blob/main/Tutorial3nadiyah24211204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Array2x2 = np.array([[10,5],
                     [7,9]])
print(Array2x2)

[[10  5]
 [ 7  9]]


In [ ]:
import numpy as np

RandomArray = np.random.rand(3,4)
print(RandomArray)


[[0.47089225 0.38065309 0.18158343 0.07992865]
 [0.07564455 0.91957107 0.30829461 0.40202228]
 [0.31501905 0.81812742 0.7963185  0.02485538]]


In [7]:
import numpy as np

ones_array = np.ones((5,4))
zeros_array = np.zeros((7,2))

print("Array of ones :", ones_array)
print("Array of zeros :", zeros_array)

Array of ones : [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of zeros : [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
Array63 = np.random.rand(6,3)
print("Random generated array", Array63)
Tarray63 = Array63.T
print("Transposed array", Tarray63)

Random generated array [[0.36217774 0.37819595 0.98112589]
 [0.1149365  0.61618999 0.06153238]
 [0.87862338 0.49167423 0.65840987]
 [0.83247521 0.72020005 0.82847575]
 [0.11977637 0.0574588  0.67548032]
 [0.7330897  0.85079506 0.51630607]]
Transposed array [[0.36217774 0.1149365  0.87862338 0.83247521 0.11977637 0.7330897 ]
 [0.37819595 0.61618999 0.49167423 0.72020005 0.0574588  0.85079506]
 [0.98112589 0.06153238 0.65840987 0.82847575 0.67548032 0.51630607]]


In [10]:

n, p, m = 2, 3, 4
Anp = np.random.rand(n, p)
Apm = np.random.rand(p, m)

DOT = np.dot(Anp, Apm)

print("Matrix 1 :", Anp)
print("\nMatrix 2 :", Apm)
print("\nDot product:", DOT)


Matrix 1 : [[0.73775898 0.52288088 0.24700035]
 [0.40858202 0.83521903 0.64309997]]

Matrix 2 : [[0.62360204 0.73183178 0.71688436 0.35219817]
 [0.06484549 0.41988876 0.55800901 0.41158726]
 [0.86972547 0.31144997 0.15090789 0.20096311]]

Dot product: [[0.70879696 0.83639552 0.85793442 0.52468643]
 [0.86827318 0.85000586 0.85601466 0.61690672]]
